# Generated by Django 3.0.4 on 2020-03-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirects_analyzer', '0002_auto_20200321_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirectinfo',
            old_name='redirect_get_paramenters',
            new_name='redirect_query',
        ),
    ]
